# -*- coding: utf-8 -*-
"""pfr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17vEMVRX3bAS-jN5YdXUoblMfQZIR53Hj
"""

# ============================================================
# AI-OPTIMIZED PFR DIGITAL TWIN
# XGBoost + Differential Evolution
# Hypothetical First-Order Reaction: A -> B
#
# INPUT FEATURES:
#   1. Temperature (K)
#   2. Pressure (bar)
#   3. Residence Time (min)
#   4. Feed Concentration (mol/L)
#
# OUTPUTS:
#   - Conversion
#   - Heating energy
#   - Reaction energy
#   - Pumping energy
#   - Total energy
#   - Solar energy utilized
#   - Grid energy
#   - CO2 emissions
#
# OPTIMIZATION:
#   Differential Evolution
#   Objective: Minimum energy
#   Constraint: Conversion >= 90%
# ============================================================


# ============================================================
# 1. INSTALL REQUIRED LIBRARIES
# ============================================================

!pip -q install xgboost scipy scikit-learn pandas numpy matplotlib joblib


# ============================================================
# 2. IMPORT LIBRARIES
# ============================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib

from scipy.optimize import differential_evolution

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

from xgboost import XGBRegressor

from IPython.display import display

np.random.seed(42)

print("All libraries loaded successfully.")


# ============================================================
# 3. HYPOTHETICAL PFR PARAMETERS
# ============================================================

# ------------------------------------------------------------
# Reactor
# ------------------------------------------------------------

REACTOR_VOLUME = 2.0       # L

# ------------------------------------------------------------
# Reaction:
#
# A -> B
#
# First-order:
#
# -rA = k CA
# ------------------------------------------------------------

# Pre-exponential factor
K0 = 2.0e6                 # 1/min

# Activation energy
EA = 50000.0               # J/mol

# Universal gas constant
R = 8.314                  # J/mol/K

# ------------------------------------------------------------
# Thermodynamic properties
# ------------------------------------------------------------

# Hypothetical heat of reaction
DELTA_H = -50000.0         # J/mol

# Heat capacity
CP = 4.18                  # J/g/K

# Density
DENSITY = 1.0              # kg/L

# ------------------------------------------------------------
# Equipment efficiencies
# ------------------------------------------------------------

PUMP_EFFICIENCY = 0.70
HEATER_EFFICIENCY = 0.90

# ------------------------------------------------------------
# Environmental parameters
# ------------------------------------------------------------

# Grid emission factor
GRID_EMISSION_FACTOR = 0.70    # kg CO2/kWh

# Available solar energy
SOLAR_ENERGY = 3.0              # kWh

print("PFR parameters initialized.")


# ============================================================
# 4. ARRHENIUS EQUATION
# ============================================================

def reaction_rate_constant(T):
    """
    Calculate first-order reaction rate constant.

    k = K0 * exp(-EA / RT)

    Parameters
    ----------
    T : float
        Temperature in Kelvin

    Returns
    -------
    k : float
        Reaction rate constant in 1/min
    """

    k = K0 * np.exp(-EA / (R * T))

    return k


# ============================================================
# 5. PFR CONVERSION MODEL
# ============================================================

def pfr_conversion(T, tau, CA0):
    """
    Calculate conversion for an isothermal
    first-order PFR.

    For first-order reaction:

        A -> B

        -rA = k CA

    PFR solution:

        X = 1 - exp(-k*tau)

    CA0 is retained as an input because it is one
    of the requested ML features.

    For this simplified first-order,
    constant-density model, conversion is
    mathematically independent of CA0.
    """

    k = reaction_rate_constant(T)

    X = 1.0 - np.exp(-k * tau)

    # Keep conversion physically meaningful
    X = np.clip(X, 0.0, 0.999999)

    return X


# ============================================================
# 6. ENERGY MODEL
# ============================================================

def calculate_energy(T, P, tau, CA0):
    """
    Calculate approximate PFR energy consumption.

    Energy components:

        1. Heating energy
        2. Reaction energy
        3. Pumping energy

    Returns
    -------
    heating_energy_kWh
    reaction_energy_kWh
    pumping_energy_kWh
    total_energy_kWh
    """

    # --------------------------------------------------------
    # Flow rate from residence time
    #
    # tau = V / Q
    #
    # Q = V / tau
    # --------------------------------------------------------

    Q = REACTOR_VOLUME / tau      # L/min

    # --------------------------------------------------------
    # Conversion
    # --------------------------------------------------------

    X = pfr_conversion(T, tau, CA0)

    # ========================================================
    # 1. HEATING ENERGY
    # ========================================================

    T_FEED = 298.15              # K

    # Mass flow
    mass_flow_kg_min = Q * DENSITY

    # Convert CP from J/g/K to J/kg/K
    CP_KG = CP * 1000

    # Sensible heating
    heating_power_J_min = (
        mass_flow_kg_min
        * CP_KG
        * max(T - T_FEED, 0)
    )

    # Convert J/min to kWh
    heating_energy_kWh = (
        heating_power_J_min
        * 60
        / 3.6e6
    )

    # Correct for heater efficiency
    heating_energy_kWh /= HEATER_EFFICIENCY

    # ========================================================
    # 2. REACTION ENERGY
    # ========================================================

    # Moles reacted per minute
    mol_reacted_min = (
        Q
        * CA0
        * X
    )

    reaction_power_J_min = (
        mol_reacted_min
        * abs(DELTA_H)
    )

    reaction_energy_kWh = (
        reaction_power_J_min
        * 60
        / 3.6e6
    )

    # ========================================================
    # 3. PUMPING ENERGY
    # ========================================================

    # Simplified pressure requirement
    delta_P = P * 1e5       # bar -> Pa

    # L/min -> m3/s
    Q_m3_s = Q * 1e-3 / 60

    pump_power_W = (
        delta_P
        * Q_m3_s
        / PUMP_EFFICIENCY
    )

    pumping_energy_kWh = pump_power_W / 1000

    # ========================================================
    # TOTAL ENERGY
    # ========================================================

    total_energy_kWh = (
        heating_energy_kWh
        + reaction_energy_kWh
        + pumping_energy_kWh
    )

    return (
        heating_energy_kWh,
        reaction_energy_kWh,
        pumping_energy_kWh,
        total_energy_kWh
    )


# ============================================================
# 7. GENERATE DIGITAL-TWIN DATASET
# ============================================================

N_SAMPLES = 10000

# Input feature ranges
temperature_values = np.random.uniform(
    310,
    380,
    N_SAMPLES
)

pressure_values = np.random.uniform(
    1,
    5,
    N_SAMPLES
)

residence_time_values = np.random.uniform(
    0.5,
    10,
    N_SAMPLES
)

feed_concentration_values = np.random.uniform(
    0.5,
    2.0,
    N_SAMPLES
)


data = []

for T, P, tau, CA0 in zip(
    temperature_values,
    pressure_values,
    residence_time_values,
    feed_concentration_values
):

    # PFR conversion
    X = pfr_conversion(
        T,
        tau,
        CA0
    )

    # Energy
    (
        E_heat,
        E_reaction,
        E_pump,
        E_total
    ) = calculate_energy(
        T,
        P,
        tau,
        CA0
    )

    data.append([
        T,
        P,
        tau,
        CA0,
        X,
        E_heat,
        E_reaction,
        E_pump,
        E_total
    ])


# ============================================================
# 8. CREATE DATAFRAME
# ============================================================

columns = [
    "Temperature_K",
    "Pressure_bar",
    "Residence_Time_min",
    "Feed_Concentration_mol_L",
    "Conversion",
    "Heating_Energy_kWh",
    "Reaction_Energy_kWh",
    "Pumping_Energy_kWh",
    "Total_Energy_kWh"
]

df = pd.DataFrame(
    data,
    columns=columns
)


print("\nDataset created successfully.")
print("Dataset shape:", df.shape)

display(df.head(10))


# ============================================================
# 9. DATASET STATISTICS
# ============================================================

print("\nDataset statistics:")
display(df.describe())


# ============================================================
# 10. DEFINE XGBOOST INPUT FEATURES
# ============================================================

features = [
    "Temperature_K",
    "Pressure_bar",
    "Residence_Time_min",
    "Feed_Concentration_mol_L"
]

X_data = df[features]


# ============================================================
# 11. TRAIN XGBOOST CONVERSION MODEL
# ============================================================

y_conversion = df["Conversion"]


X_train_X, X_test_X, y_train_X, y_test_X = train_test_split(
    X_data,
    y_conversion,
    test_size=0.20,
    random_state=42
)


xgb_conversion = XGBRegressor(
    n_estimators=400,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="reg:squarederror",
    random_state=42
)


xgb_conversion.fit(
    X_train_X,
    y_train_X
)


# Predictions
pred_conversion = xgb_conversion.predict(
    X_test_X
)


# Metrics
conversion_mae = mean_absolute_error(
    y_test_X,
    pred_conversion
)

conversion_rmse = np.sqrt(
    mean_squared_error(
        y_test_X,
        pred_conversion
    )
)

conversion_r2 = r2_score(
    y_test_X,
    pred_conversion
)


print("\n==============================")
print("XGBOOST CONVERSION MODEL")
print("==============================")

print(
    f"MAE  : {conversion_mae:.8f}"
)

print(
    f"RMSE : {conversion_rmse:.8f}"
)

print(
    f"R²   : {conversion_r2:.8f}"
)


# ============================================================
# 12. TRAIN XGBOOST ENERGY MODEL
# ============================================================

y_energy = df["Total_Energy_kWh"]


X_train_E, X_test_E, y_train_E, y_test_E = train_test_split(
    X_data,
    y_energy,
    test_size=0.20,
    random_state=42
)


xgb_energy = XGBRegressor(
    n_estimators=400,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="reg:squarederror",
    random_state=42
)


xgb_energy.fit(
    X_train_E,
    y_train_E
)


# Predictions
pred_energy = xgb_energy.predict(
    X_test_E
)


# Metrics
energy_mae = mean_absolute_error(
    y_test_E,
    pred_energy
)

energy_rmse = np.sqrt(
    mean_squared_error(
        y_test_E,
        pred_energy
    )
)

energy_r2 = r2_score(
    y_test_E,
    pred_energy
)


print("\n==============================")
print("XGBOOST ENERGY MODEL")
print("==============================")

print(
    f"MAE  : {energy_mae:.8f} kWh"
)

print(
    f"RMSE : {energy_rmse:.8f} kWh"
)

print(
    f"R²   : {energy_r2:.8f}"
)


# ============================================================
# 13. ACTUAL VS PREDICTED CONVERSION
# ============================================================

plt.figure(figsize=(7, 6))

plt.scatter(
    y_test_X,
    pred_conversion,
    alpha=0.4
)

plt.plot(
    [0, 1],
    [0, 1],
    linestyle="--"
)

plt.xlabel(
    "Actual Conversion"
)

plt.ylabel(
    "Predicted Conversion"
)

plt.title(
    "XGBoost: Actual vs Predicted Conversion"
)

plt.grid(alpha=0.2)

plt.show()


# ============================================================
# 14. ACTUAL VS PREDICTED ENERGY
# ============================================================

plt.figure(figsize=(7, 6))

plt.scatter(
    y_test_E,
    pred_energy,
    alpha=0.4
)

min_energy = min(
    y_test_E.min(),
    pred_energy.min()
)

max_energy = max(
    y_test_E.max(),
    pred_energy.max()
)

plt.plot(
    [min_energy, max_energy],
    [min_energy, max_energy],
    linestyle="--"
)

plt.xlabel(
    "Actual Energy (kWh)"
)

plt.ylabel(
    "Predicted Energy (kWh)"
)

plt.title(
    "XGBoost: Actual vs Predicted Energy"
)

plt.grid(alpha=0.2)

plt.show()


# ============================================================
# 15. DIFFERENTIAL EVOLUTION OBJECTIVE FUNCTION
# ============================================================

CONVERSION_TARGET = 0.90


def optimization_objective(params):

    # Extract optimization variables
    T, P, tau, CA0 = params

    # Create input DataFrame
    input_df = pd.DataFrame(
        [[T, P, tau, CA0]],
        columns=features
    )

    # XGBoost predictions
    predicted_conversion = float(
        xgb_conversion.predict(
            input_df
        )[0]
    )

    predicted_energy = float(
        xgb_energy.predict(
            input_df
        )[0]
    )

    # --------------------------------------------------------
    # Conversion constraint
    #
    # X >= 0.90
    # --------------------------------------------------------

    if predicted_conversion < CONVERSION_TARGET:

        deficit = (
            CONVERSION_TARGET
            - predicted_conversion
        )

        penalty = 10000 * deficit**2

        return (
            predicted_energy
            + penalty
        )

    # If conversion requirement is satisfied
    return predicted_energy


# ============================================================
# 16. DEFINE OPTIMIZATION BOUNDS
# ============================================================

bounds = [

    # Temperature
    (310, 380),

    # Pressure
    (1, 5),

    # Residence time
    (0.5, 10),

    # Feed concentration
    (0.5, 2.0)
]


print("\nOptimization variables:")
print("Temperature       : 310 - 380 K")
print("Pressure          : 1 - 5 bar")
print("Residence time    : 0.5 - 10 min")
print("Feed concentration: 0.5 - 2 mol/L")
print("Conversion target  : >= 90%")


# ============================================================
# 17. RUN DIFFERENTIAL EVOLUTION
# ============================================================

print("\nRunning Differential Evolution...")
print("Please wait...")


result = differential_evolution(
    optimization_objective,
    bounds,
    strategy="best1bin",
    maxiter=100,
    popsize=15,
    mutation=(0.5, 1.0),
    recombination=0.7,
    seed=42,
    polish=True
)


# Extract optimized variables
optimal_T = result.x[0]
optimal_P = result.x[1]
optimal_tau = result.x[2]
optimal_CA0 = result.x[3]


print("\nOptimization completed.")


# ============================================================
# 18. PREDICT OPTIMIZED PERFORMANCE
# ============================================================

optimal_input = pd.DataFrame(
    [[
        optimal_T,
        optimal_P,
        optimal_tau,
        optimal_CA0
    ]],
    columns=features
)


optimized_conversion = float(
    xgb_conversion.predict(
        optimal_input
    )[0]
)


optimized_energy = float(
    xgb_energy.predict(
        optimal_input
    )[0]
)


# Calculate detailed energy using PFR model
(
    optimized_heating_energy,
    optimized_reaction_energy,
    optimized_pumping_energy,
    optimized_physics_energy
) = calculate_energy(
    optimal_T,
    optimal_P,
    optimal_tau,
    optimal_CA0
)


# ============================================================
# 19. DISPLAY OPTIMIZED PFR CONDITIONS
# ============================================================

print("\n")
print("==============================================")
print("       AI-OPTIMIZED PFR OPERATING POINT")
print("==============================================")

print(
    f"Temperature        : {optimal_T:.3f} K"
)

print(
    f"Pressure           : {optimal_P:.3f} bar"
)

print(
    f"Residence time     : {optimal_tau:.3f} min"
)

print(
    f"Feed concentration : {optimal_CA0:.3f} mol/L"
)

print("----------------------------------------------")

print(
    f"Predicted conversion: "
    f"{optimized_conversion*100:.3f}%"
)

print(
    f"Predicted energy   : "
    f"{optimized_energy:.6f} kWh"
)

print("----------------------------------------------")

print(
    f"Heating energy     : "
    f"{optimized_heating_energy:.6f} kWh"
)

print(
    f"Reaction energy    : "
    f"{optimized_reaction_energy:.6f} kWh"
)

print(
    f"Pumping energy     : "
    f"{optimized_pumping_energy:.6f} kWh"
)

print(
    f"Physics-model total: "
    f"{optimized_physics_energy:.6f} kWh"
)

print("----------------------------------------------")


if optimized_conversion >= CONVERSION_TARGET:

    print(
        "✓ SUCCESS: Conversion target of "
        "90% has been achieved."
    )

else:

    print(
        "✗ Conversion target was not achieved."
    )


# ============================================================
# 20. SOLAR ENERGY ANALYSIS
# ============================================================

solar_used = min(
    SOLAR_ENERGY,
    optimized_energy
)

grid_energy = max(
    optimized_energy - SOLAR_ENERGY,
    0
)


optimized_CO2 = (
    grid_energy
    * GRID_EMISSION_FACTOR
)


print("\n")
print("==============================================")
print("             SOLAR ENERGY ANALYSIS")
print("==============================================")


print(
    f"Total energy required : "
    f"{optimized_energy:.6f} kWh"
)

print(
    f"Solar energy available: "
    f"{SOLAR_ENERGY:.6f} kWh"
)

print(
    f"Solar energy utilized : "
    f"{solar_used:.6f} kWh"
)

print(
    f"Grid energy required  : "
    f"{grid_energy:.6f} kWh"
)

print(
    f"CO2 emissions         : "
    f"{optimized_CO2:.6f} kg CO2e"
)


# ============================================================
# 21. BASELINE REACTOR
# ============================================================

# Conventional operating point
#
# This is only a hypothetical baseline.

baseline_T = 360
baseline_P = 3
baseline_tau = 5
baseline_CA0 = 1.0


baseline_input = pd.DataFrame(
    [[
        baseline_T,
        baseline_P,
        baseline_tau,
        baseline_CA0
    ]],
    columns=features
)


baseline_conversion = float(
    xgb_conversion.predict(
        baseline_input
    )[0]
)


baseline_energy = float(
    xgb_energy.predict(
        baseline_input
    )[0]
)


# Assume baseline uses only grid electricity
baseline_grid_energy = baseline_energy


baseline_CO2 = (
    baseline_grid_energy
    * GRID_EMISSION_FACTOR
)


# ============================================================
# 22. CALCULATE SAVINGS
# ============================================================

energy_saving = (
    baseline_energy
    - optimized_energy
)


if baseline_energy > 0:

    energy_saving_percent = (
        energy_saving
        / baseline_energy
    ) * 100

else:

    energy_saving_percent = 0


CO2_reduction = (
    baseline_CO2
    - optimized_CO2
)


if baseline_CO2 > 0:

    CO2_reduction_percent = (
        CO2_reduction
        / baseline_CO2
    ) * 100

else:

    CO2_reduction_percent = 0


# ============================================================
# 23. BASELINE VS OPTIMIZED RESULTS
# ============================================================

print("\n")
print("==============================================")
print("        BASELINE VS AI-OPTIMIZED PFR")
print("==============================================")


print("\nBASELINE")
print("----------------------------------------------")

print(
    f"Temperature        : "
    f"{baseline_T:.2f} K"
)

print(
    f"Pressure           : "
    f"{baseline_P:.2f} bar"
)

print(
    f"Residence time     : "
    f"{baseline_tau:.2f} min"
)

print(
    f"Feed concentration : "
    f"{baseline_CA0:.2f} mol/L"
)

print(
    f"Conversion         : "
    f"{baseline_conversion*100:.3f}%"
)

print(
    f"Energy             : "
    f"{baseline_energy:.6f} kWh"
)

print(
    f"CO2                : "
    f"{baseline_CO2:.6f} kg CO2e"
)


print("\nAI OPTIMIZED")
print("----------------------------------------------")

print(
    f"Temperature        : "
    f"{optimal_T:.2f} K"
)

print(
    f"Pressure           : "
    f"{optimal_P:.2f} bar"
)

print(
    f"Residence time     : "
    f"{optimal_tau:.2f} min"
)

print(
    f"Feed concentration : "
    f"{optimal_CA0:.2f} mol/L"
)

print(
    f"Conversion         : "
    f"{optimized_conversion*100:.3f}%"
)

print(
    f"Energy             : "
    f"{optimized_energy:.6f} kWh"
)

print(
    f"Solar utilized     : "
    f"{solar_used:.6f} kWh"
)

print(
    f"Grid energy        : "
    f"{grid_energy:.6f} kWh"
)

print(
    f"CO2                : "
    f"{optimized_CO2:.6f} kg CO2e"
)


print("\nSUSTAINABILITY IMPACT")
print("----------------------------------------------")

print(
    f"Energy saved       : "
    f"{energy_saving:.6f} kWh"
)

print(
    f"Energy reduction   : "
    f"{energy_saving_percent:.2f}%"
)

print(
    f"CO2 reduced        : "
    f"{CO2_reduction:.6f} kg CO2e"
)

print(
    f"CO2 reduction      : "
    f"{CO2_reduction_percent:.2f}%"
)


# ============================================================
# 24. CONVERSION VS RESIDENCE TIME
# ============================================================

tau_values = np.linspace(
    0.5,
    10,
    200
)


conversion_values = []


for tau in tau_values:

    X = pfr_conversion(
        optimal_T,
        tau,
        optimal_CA0
    )

    conversion_values.append(
        X * 100
    )


plt.figure(figsize=(8, 5))

plt.plot(
    tau_values,
    conversion_values,
    label="PFR conversion"
)

plt.axhline(
    90,
    linestyle="--",
    label="90% Target"
)

plt.axvline(
    optimal_tau,
    linestyle=":",
    label="Optimized Residence Time"
)

plt.xlabel(
    "Residence Time (min)"
)

plt.ylabel(
    "Conversion (%)"
)

plt.title(
    "PFR Conversion vs Residence Time"
)

plt.legend()

plt.grid(alpha=0.2)

plt.show()


# ============================================================
# 25. TEMPERATURE VS CONVERSION
# ============================================================

temperature_plot = np.linspace(
    310,
    380,
    200
)


temperature_conversion = []


for T in temperature_plot:

    X = pfr_conversion(
        T,
        optimal_tau,
        optimal_CA0
    )

    temperature_conversion.append(
        X * 100
    )


plt.figure(figsize=(8, 5))

plt.plot(
    temperature_plot,
    temperature_conversion
)

plt.axhline(
    90,
    linestyle="--",
    label="90% Target"
)

plt.axvline(
    optimal_T,
    linestyle=":",
    label="Optimized Temperature"
)

plt.xlabel(
    "Temperature (K)"
)

plt.ylabel(
    "Conversion (%)"
)

plt.title(
    "PFR Conversion vs Temperature"
)

plt.legend()

plt.grid(alpha=0.2)

plt.show()


# ============================================================
# 26. BASELINE VS OPTIMIZED ENERGY
# ============================================================

plt.figure(figsize=(7, 5))

plt.bar(
    [
        "Baseline",
        "AI Optimized"
    ],
    [
        baseline_energy,
        optimized_energy
    ]
)

plt.ylabel(
    "Energy Consumption (kWh)"
)

plt.title(
    "Baseline vs AI-Optimized PFR Energy"
)

plt.grid(
    axis="y",
    alpha=0.2
)

plt.show()


# ============================================================
# 27. BASELINE VS OPTIMIZED CO2
# ============================================================

plt.figure(figsize=(7, 5))

plt.bar(
    [
        "Baseline",
        "AI Optimized"
    ],
    [
        baseline_CO2,
        optimized_CO2
    ]
)

plt.ylabel(
    "CO2 Emissions (kg CO2e)"
)

plt.title(
    "Baseline vs AI-Optimized PFR CO2 Emissions"
)

plt.grid(
    axis="y",
    alpha=0.2
)

plt.show()


# ============================================================
# 28. FEATURE IMPORTANCE - CONVERSION
# ============================================================

importance_conversion = pd.Series(
    xgb_conversion.feature_importances_,
    index=features
).sort_values(
    ascending=True
)


plt.figure(figsize=(8, 5))

importance_conversion.plot(
    kind="barh"
)

plt.xlabel(
    "Feature Importance"
)

plt.title(
    "XGBoost Feature Importance for Conversion"
)

plt.grid(
    axis="x",
    alpha=0.2
)

plt.show()


# ============================================================
# 29. FEATURE IMPORTANCE - ENERGY
# ============================================================

importance_energy = pd.Series(
    xgb_energy.feature_importances_,
    index=features
).sort_values(
    ascending=True
)


plt.figure(figsize=(8, 5))

importance_energy.plot(
    kind="barh"
)

plt.xlabel(
    "Feature Importance"
)

plt.title(
    "XGBoost Feature Importance for Energy"
)

plt.grid(
    axis="x",
    alpha=0.2
)

plt.show()


# ============================================================
# 30. CREATE FINAL RESULTS TABLE
# ============================================================

results_table = pd.DataFrame({
    "Parameter": [
        "Temperature",
        "Pressure",
        "Residence Time",
        "Feed Concentration",
        "Conversion",
        "Total Energy",
        "Solar Energy Used",
        "Grid Energy",
        "CO2 Emissions"
    ],

    "Optimized Value": [
        f"{optimal_T:.3f} K",
        f"{optimal_P:.3f} bar",
        f"{optimal_tau:.3f} min",
        f"{optimal_CA0:.3f} mol/L",
        f"{optimized_conversion*100:.3f} %",
        f"{optimized_energy:.6f} kWh",
        f"{solar_used:.6f} kWh",
        f"{grid_energy:.6f} kWh",
        f"{optimized_CO2:.6f} kg CO2e"
    ]
})


print("\n")
print("==============================================")
print("              FINAL RESULT TABLE")
print("==============================================")

display(results_table)


# ============================================================
# 31. SAVE MODELS
# ============================================================

joblib.dump(
    xgb_conversion,
    "pfr_xgboost_conversion.pkl"
)

joblib.dump(
    xgb_energy,
    "pfr_xgboost_energy.pkl"
)


# Save dataset
df.to_csv(
    "pfr_training_dataset.csv",
    index=False
)


print("\nFiles saved:")
print("1. pfr_xgboost_conversion.pkl")
print("2. pfr_xgboost_energy.pkl")
print("3. pfr_training_dataset.csv")


# ============================================================
# 32. SIMPLE USER PREDICTION FUNCTION
# ============================================================

def predict_pfr(
    temperature,
    pressure,
    residence_time,
    feed_concentration
):
    """
    Give operating conditions and receive
    predicted PFR performance.
    """

    user_input = pd.DataFrame(
        [[
            temperature,
            pressure,
            residence_time,
            feed_concentration
        ]],
        columns=features
    )

    conversion = float(
        xgb_conversion.predict(
            user_input
        )[0]
    )

    energy = float(
        xgb_energy.predict(
            user_input
        )[0]
    )

    solar = min(
        SOLAR_ENERGY,
        energy
    )

    grid = max(
        energy - SOLAR_ENERGY,
        0
    )

    co2 = (
        grid
        * GRID_EMISSION_FACTOR
    )

    print("\n================================")
    print("PFR PREDICTION")
    print("================================")

    print(
        f"Temperature        : "
        f"{temperature:.2f} K"
    )

    print(
        f"Pressure           : "
        f"{pressure:.2f} bar"
    )

    print(
        f"Residence time     : "
        f"{residence_time:.2f} min"
    )

    print(
        f"Feed concentration : "
        f"{feed_concentration:.2f} mol/L"
    )

    print("--------------------------------")

    print(
        f"Predicted conversion: "
        f"{conversion*100:.2f}%"
    )

    print(
        f"Predicted energy    : "
        f"{energy:.6f} kWh"
    )

    print(
        f"Solar energy used   : "
        f"{solar:.6f} kWh"
    )

    print(
        f"Grid energy         : "
        f"{grid:.6f} kWh"
    )

    print(
        f"CO2 emissions       : "
        f"{co2:.6f} kg CO2e"
    )

    if conversion >= 0.90:

        print(
            "\n✓ Conversion requirement satisfied."
        )

    else:

        print(
            "\n✗ Conversion below 90%."
        )

    return {
        "conversion": conversion,
        "energy_kWh": energy,
        "solar_kWh": solar,
        "grid_kWh": grid,
        "CO2_kg": co2
    }


# ============================================================
# 33. EXAMPLE USER INPUT
# ============================================================

# You can change these values.

example_result = predict_pfr(
    temperature=340,
    pressure=2.5,
    residence_time=4,
    feed_concentration=1.0
)


# ============================================================
# END OF PROGRAM
# ============================================================

print("\n==============================================")
print("       PFR AI DIGITAL TWIN COMPLETED")
print("==============================================")